name: Build LaTeX document

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/latex
              with:
                  args: latexmk -pdf -interaction=batchmode -output-directory="$(pwd)/build" report.tex
            - uses: actions/upload-artifact@v2
              with:
                  name: Passive Radar Paper
                  path: build/report.pdf
    build_beamer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/latex
              with:
                  args: latexmk -pdf -interaction=batchmode -output-directory="$(pwd)/build" beamer.tex
            - uses: actions/upload-artifact@v2
              with:
                  name: Passive Radar Presentation
                  path: build/beamer.pdf
